# Generated by Django 4.1.7 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('nick_name', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Пол')),
                ('custom_gender', models.CharField(blank=True, max_length=50, verbose_name='Пользовательский пол')),
            ],
            options={
                'verbose_name': 'Пользователь приложения',
                'verbose_name_plural': 'Пользователи приложения',
                'ordering': ['id', 'nick_name'],
            },
        ),
    ]
